### ISSUE TITLE
Problems during Cluster Deplyment

### ISSUE THREAD

**Issue by rnavarromatesanz** [Azure/feast-azure#60]
Hi,

I'm trying to deplu the cluster following the example provided in th setup page
https://github.com/Azure/feast-azure/blob/main/cluster/setup/README.md

Here I've got a couple of problems.

1. I'm not able to find de service "**internal-feast-core**" among the service deployed during installation. As workaround, I'm asssuming that the IP provided at the end of installation, It's the IP needed: 

_You can now access the Feast service with ip 10.244.0.8:6565 within the same virtual network where the AKS cluster is deployed to._

2 Assuming the previous IP, during the testing, I've got a final error during the apply process with this error

> /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
> Traceback (most recent call last):
>   File "/home/nttdataadmin/.local/lib/python3.8/site-packages/feast/grpc/grpc.py", line 48, in create_grpc_channel
>     grpc.channel_ready_future(channel).result(timeout=timeout)
>   File "/home/nttdataadmin/.local/lib/python3.8/site-packages/grpc/_utilities.py", line 140, in result
>     self._block(timeout)
>   File "/home/nttdataadmin/.local/lib/python3.8/site-packages/grpc/_utilities.py", line 86, in _block
>     raise grpc.FutureTimeoutError()
> grpc.FutureTimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_featurestore.py", line 71, in <module>
>     client.apply(driver_id)
>   File "/home/nttdataadmin/.local/lib/python3.8/site-packages/feast/client.py", line 516, in apply
>     log_usage("apply", self._telemetry_id, datetime.utcnow(), self.version())
>   File "/home/nttdataadmin/.local/lib/python3.8/site-packages/feast/client.py", line 372, in version
>     serving_version = self._serving_service.GetFeastServingInfo(
>   File "/home/nttdataadmin/.local/lib/python3.8/site-packages/feast/client.py", line 184, in _serving_service
>     channel = create_grpc_channel(
>   File "/home/nttdataadmin/.local/lib/python3.8/site-packages/feast/grpc/grpc.py", line 51, in create_grpc_channel
>     raise ConnectionError(
> ConnectionError: Connection timed out while attempting to connect to localhost:6566
> 

¿Can you give me any advice?

Regards and Thanks in advance
Roberto

**Comment by samuel100** [comment]
@xiaoyongzhumsft any advice here?

**Comment by Rakesh-Raushan** [comment]
Facing the same error, @rnavarromatesanz by any chance were you able to resolve this?

**Comment by rnavarromatesanz** [comment]
No, I didn't find any solution...
